Develop
segheim/MJCSchool pull request #2
Opened 2022-02-02 08:32 UTC by segheim

2022-02-02 09:23 UTC, senator2202 requested changes

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/service/GiftCertificateService.java
> +public interface GiftCertificateService extends GCSService<GiftCertificate> {
Store interfaces in package root, store there implementations in subpackage "impl".
Example: 
![image](https://user-images.githubusercontent.com/39515729/152125325-1cc307db-9b67-431b-ba48-7740af248683.png)

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/service/GiftCertificateServiceImpl.java
> +    @Transactional(rollbackFor = ServiceException.class)
rollback for this exception is redundant, as there is nothing to rollback if this exception is thrown. It us just validation exception

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/model/GiftCertificate.java
> +    public GiftCertificate(String name, String description, BigDecimal price,
Remove constructors, that you don't use. The same for all entities

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/model/PatchGiftCertificate.java
> +public class PatchGiftCertificate {
I don't understand why do you need this class. You can use GiftCertificate class for patch purposes

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/model/ResponseException.java
> +public class ResponseException {
Is it correct place for this Exception class?

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/dao/CrdRepository.java
> +public interface CrdRepository<T> {
Why Crd? Why not Crud? This name "CrdRepository" is not obvious

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/config/WebConfig.java
> +//        AnnotationConfigWebApplicationContext rootContext = new AnnotationConfigWebApplicationContext();
Remove this code if you don't need it

2022-02-02 09:23 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/config/ApplicationConfig.java
> +        DriverManagerDataSource dataSource = new DriverManagerDataSource();
Move this hardcoded datasource parameters into property file, and use properties in dataSource configuration

2022-02-03 10:14 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/web/GiftCertificateController.java
> +        if (giftCertificate.getName() == null) {
Move all validation logic into separte util class and call validation logic from service layer

2022-02-03 10:32 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/service/Impl/GiftCertificateServiceImpl.java
> +    private boolean isValidSortName(String sortName) {
move validation into validation class

2022-02-03 10:34 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/service/Impl/GiftCertificateServiceImpl.java
> +                .stream()
.forEach() can be applied to collections without casting them tthem to Stream object.

2022-02-03 18:05 UTC, senator2202 requested changes

2022-02-03 18:05 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/model/ResponseControllerHandlerExceptionAdvice.java
> +public class ResponseControllerHandlerExceptionAdvice {
As I can see, this is simple POJO, don't name it with "Advice" suffix. It is a little bit confusing

2022-02-03 19:45 UTC, Lavazz commented on src/main/java/com/epam/esm/giftcertificatesystem/config/ApplicationConfig.java
> +        dataSource.setUsername(environment.getProperty("db.name"));
could you please make parameters as constants.

2022-02-09 06:50 UTC, senator2202 commented on src/main/java/com/epam/esm/giftcertificatesystem/service/GCSService.java
> +    Optional<T> add(T t) throws ServiceException;
I can not see, where Service Exception can thrown. Please double check all such cases and remove this declaration, if Exception is not thrown

2022-02-09 06:52 UTC, senator2202 requested changes
- Remove unused exceptions from method declarations
- Remove all commented pieces of code

2022-02-10 18:13 UTC, senator2202 requested changes
Please, resolve last issues

2022-02-11 15:22 UTC, senator2202 approved these changes

2022-02-11 15:23 UTC, merged

2022-02-11 16:32 UTC, segheim commented
Thanks for your comments!